### ISSUE TITLE
Form label I18n

### ISSUE THREAD

**Issue by jerefrer** [nebirhos/activeadmin-seo#3]
Hi again,

I wanted to change the "slug" form label because I don't think the client will understand what it means ...

But it was actually quite a pain to figure out what was the exact path to use in the I18n YML file.
So, in case someone would need it in the future, here it is :

``` YML
en:
  activerecord:
    attributes:
      active_admin/seo/meta:
        slug: Title in URL
```

Maybe you could add this to the README or some Wiki page ?
